chart-dirs:
  - ./
chart-repos:
  - stable=https://charts.helm.sh/stable
  - bitnami=https://charts.bitnami.com/bitnami
  - grafana=https://grafana.github.io/helm-charts
debug: true
excluded-charts: []
remote: origin
