apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
data: 
  proxysql.cnf: |
    {{- tpl (.Files.Get "files/proxysql.cnf") . | nindent 4 }}
