---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
{{ include "proxysql.labels" . | indent 4 }}
data:
  proxysql.cnf: {{ include "proxysql.conf" . | b64enc }}
{{- if not .Values.ssl.fromSecret -}}
  {{- with .Values.ssl.ca }}
  ca.pem: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.ssl.cert }}
  cert.pem: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.ssl.key }}
  key.pem: {{ . | b64enc }}
  {{- end -}}
{{- end -}}
