{{- if (include "pullsecrets.createSecret" .) -}}
{{- if and .Values.gcr.enabled .Values.gcr.locations }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gcr.secretName }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        {{- include "pullsecrets.gcr" . }}
      }
    }
{{- end -}}
{{- end -}}
