{{- if and .Values.gcr.enabled }}
{{- range .Values.gcr.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        {{- $gcr := list -}}
        {{- $gcrSAKey := ternary (.serviceAccountKey | b64dec) .serviceAccountKey (.keyIsBase64 | default false) | trim -}}
            {{- range (.locations | default $.Values.gcr.defaultLocations) -}}
                {{- $auth := dict "username" "_json_key" "password" $gcrSAKey "email" (include "pullsecrets.fullname" $) "auth" (printf "_json_key:%s" $gcrSAKey | b64enc) -}}
                {{- $gcr = append $gcr (printf "%q:%s" . ($auth | toJson)) -}}
            {{- end -}}
        {{- $gcr | join ", " }}
      }
    }
{{- end -}}
{{- end -}}
