---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafkamagic.fullname" . }}
  labels:
{{ include "kafkamagic.labels" . | indent 4 }}
type: Opaque
data:
  KMAGIC_CONFIG_ENCRYPTION_KEY: {{ if .Values.config.CONFIG_ENCRYPTION_KEY }}{{ .Values.config.CONFIG_ENCRYPTION_KEY | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
{{- range $key, $value := omit .Values.config "CONFIG_ENCRYPTION_KEY" }}
  KMAGIC_{{ $key }}: {{ $value | b64enc }}
{{- end }}
{{/*
# {{- if .Values.ingress.auth.users }}
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ include "kafkamagic.fullname" . }}-auth
#   labels:
# {{ include "kafkamagic.labels" . | indent 4 }}
# type: Opaque
# data:
#   {{- $htpasswd := list -}}
#   {{- range $user, $pass := .Values.ingress.auth.users -}}
#   {{- $htpasswd := htpasswd $user $path -}}
#   {{- end -}}
#   auth: |
#     {{- $htpasswd | join "\n" | nindent 4 }}
# {{- end }}
*/}}
