{{- range .Values.pullsecrets -}}
{{/*
Generates a comma-separated ~/docker/config.json auth lines for GCR
Note: that jsonKey must be base64 encoded
*/}}
{{- $gcr := list -}}
{{- range .gcr -}}
  {{- $locations := .locations | default $.Values.gcr.locations -}}
  {{- $jsonKey := .jsonKey -}}
  {{- range $locations -}}
    {{- $auth := dict "username" "_json_key" "password" ($jsonKey | b64dec) -}}
    {{- $gcr = append $gcr (printf "%q: %s" . ($auth | toJson)) -}}
  {{- end -}}
{{- end -}}
{{- $generic := list -}}
{{- range $registry, $auth := .auths -}}
{{- $generic = append $generic (printf "%q: %s" $registry (include "pullsecrets.render.toJson" (dict "value" $auth "context" $))) -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        {{- concat $gcr $generic | join ",\n" | nindent 8 }}
      }
    }
{{- end -}}
