{{- range .Values.pullsecrets -}}
{{/*
Generates a comma-separated ~/docker/config.json auth lines for GCR
Note: that jsonKey must be base64 encoded
*/}}
{{- $gcr := list -}}
{{- range .gcr -}}
  {{- $locations := .locations | default $.Values.gcr.locations -}}
  {{- $jsonKey := .jsonKey -}}
  {{- range $locations -}}
    {{- $auth := dict "username" "_json_key" "password" ($jsonKey | b64dec) -}}
    {{- $gcr = append $gcr (printf "%q:%s" . ($auth | toJson)) -}}
  {{- end -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        {{- $gcr | join ",\n" | nindent 8 -}}
      }
    }
{{- end -}}
