apiVersion: v2
name: pullsecrets
description: A Helm chart for Kubernetes
type: application
version: 0.3.0
appVersion: 1.16.0

sources:
  - https://github.com/dysnix/charts
maintainers:
  - email: services@dysnix.com
    name: Dysnix

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
