apiVersion: v2
name: pullsecrets
description: A Helm chart for Kubernetes
type: application
version: 0.3.1
appVersion: 1.16.0

sources:
  - https://github.com/dysnix/charts
maintainers:
  - email: services@dysnix.com
    name: Dysnix
