{{- if .Values.bsc.daemonsetEnabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "bsc.fullname" . }}
  labels:
{{ include "bsc.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bsc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      bsc/chain: {{ .Values.bsc.chain }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bsc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        bsc/chain: {{ .Values.bsc.chain }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        cloud.google.com/gke-ephemeral-storage-local-ssd: "true"
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.bscCmdOverride }}
        command: [ "{{ .Values.bscCmd }}" ]
        {{- end }}
        args:
          - --config=/config/config.toml
          - --datadir={{ .Values.bsc.base_path }}
          - --syncmode={{ .Values.bsc.syncmode }}
          - --gcmode={{ .Values.bsc.gcmode }}
          - --maxpeers={{ .Values.bsc.maxpeers }}
          - --cache={{ .Values.bsc.cache }}
          - --snapshot=false
          - --port={{ .Values.service.p2pPort0 }}
          - --rpc.allow-unprotected-txs
          - --txlookuplimit=0
          - --cache.preimages
          {{- if and .Values.externalLBp2p .Values.externalLBp2pIP }}
          - --nat=extip:{{- .Values.externalLBp2pIP -}}
          {{- end }}
          {{- if .Values.bsc.noDiscovery }}
          - --nodiscover
          {{- end }}
          {{- if .Values.bsc.netrestrict }}
          - --netrestrict={{ .Values.bsc.netrestrict }}
          {{- end }}
          {{- if .Values.bsc.metrics.enabled }}
          - --metrics
          - --pprof
          - --pprof.addr=0.0.0.0
          - --pprof.port={{ .Values.bsc.metrics.service.port }}
          {{- end }}
        workingDir: "{{ .Values.bsc.base_path }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
          {{- range $val := .Values.service.ports }}
        - containerPort: {{ $val.port }}
          {{- if $val.hostPort }}
          hostPort: {{ $val.hostPort }}
          {{- end }}
          name: "{{ $val.name }}"
          protocol: {{ $val.protocol | default "TCP" }}
          {{- end }}
        volumeMounts:
        - name: bsc-config
          mountPath: /config
        - name: scripts
          mountPath: /scripts
        - name: bsc-data
          mountPath: {{ .Values.bsc.base_path }}
        {{- if .Values.livenessProbe }}
        startupProbe:
          exec:
            command:
            - /bin/sh
            - /scripts/check_node_health.sh
            - http://127.0.0.1:{{ .Values.service.rpcPort }}
            - "300"
            - last_synced_block.txt
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /scripts/check_node_health.sh
            - http://127.0.0.1:{{ .Values.service.rpcPort }}
            - "300"
            - last_synced_block.txt
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}

        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - /scripts/check_node_readiness.sh
            - --timestamp-distinct
            - "{{ .Values.bsc.readinessProbeTimestampDistinct }}"
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
      - name: logger
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ "tail","-F","{{ .Values.bsc.base_path }}/bsc.log" ]
        workingDir: "{{ .Values.bsc.base_path }}"
        volumeMounts:
          - name: bsc-data
            mountPath: {{ .Values.bsc.base_path }}
            readOnly: true
      {{- if .Values.metrics.enabled }}
      - name: metrics
        image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
        args:
          - -url
          - http://127.0.0.1:{{ .Values.service.rpcPort }}
      {{- end }}
      {{- if .Values.failback.enabled }}
      - name: nginx
        image: "{{ .Values.failback.image.repository }}:{{ .Values.failback.image.tag }}"
        imagePullPolicy: {{ .Values.failback.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.failback.port }}
            name: nginx
            protocol: TCP
        volumeMounts:
          - mountPath: /etc/nginx/
            name: nginx-config-volume
      {{- end }}
      {{- if .Values.failback.metrics.enabled }}
      - name: nginx-metrics
        image: "{{ .Values.failback.metrics.image.repository }}:{{ .Values.failback.metrics.image.tag }}"
        imagePullPolicy: {{ .Values.failback.metrics.image.pullPolicy }}
        args:
          - -nginx.scrape-uri=http://localhost:{{ .Values.failback.port }}/metrics
        ports:
          - containerPort: {{ .Values.failback.metrics.service.port }}
            name: {{ .Values.failback.metrics.service.name }}
            protocol: TCP
      {{- end }}
      initContainers:
      - name: init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c", "wget -O {{ .Values.bsc.base_path }}/geth.tar {{ .Values.bsc.snapshotUrl }} &&
        tar -xf {{ .Values.bsc.base_path }}/geth.tar -C {{ .Values.bsc.base_path }}"]
        volumeMounts:
          - name: bsc-data
            mountPath: {{ .Values.bsc.base_path }}
      - name: remove-lock
        command:
          - rm
          - -f
          - {{ .Values.bsc.base_path }}/geth/LOCK
        image: busybox
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: bsc-data
            mountPath: {{ .Values.bsc.base_path }}
      - name: get-nodekey
        command:
          - python
          - /scripts/get_nodekey.py
        image: python:slim
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: bsc-data
            mountPath: {{ .Values.bsc.base_path }}
          - name: scripts
            mountPath: /scripts
      volumes:
        - name: bsc-config
          configMap:
            name: "{{ .Release.Name }}-config"
        - name: scripts
          configMap:
            name: "{{ .Release.Name }}-scripts"
        - name: bsc-data
          emptyDir: {}
        {{- if .Values.failback.enabled }}
        - name: nginx-config-volume
          configMap:
            name: "{{ .Release.Name }}-nginx-config"
        {{- end }}
  {{- if .Values.persistence.enabled }}
  {{- end }}
{{- end }}
