{{- if .Values.bxgateway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name:  "{{ .Release.Name }}-bxgateway-certs"
type: Opaque
data:
  {{ .Values.bxgateway.certs.name0 }}: |-
{{ .Values.bxgateway.certs.value0 | b64enc | indent 4 }}
  {{ .Values.bxgateway.certs.name1 }}: |-
{{ .Values.bxgateway.certs.value1 | b64enc | indent 4 }}
{{- end }}
