apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "bsc.labels" . | indent 4 }}
spec:
  type:  {{ .Values.service.type }}
  ports:
  {{- range $val := .Values.service.ports }}
  - port: {{ $val.port }}
    name: "{{ $val.name }}"
    protocol: {{ $val.protocol | default "TCP" }}
  {{- end }}
  {{- if .Values.failback.metrics.enabled }}
  - port: {{ .Values.failback.metrics.service.port }}
    name: {{ .Values.failback.metrics.service.name }}
    protocol: "TCP"
    targetPort: {{ .Values.failback.metrics.service.port }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "bsc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
