{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kafkamagic.serviceAccountName" . }}
  labels:
{{ include "kafkamagic.labels" . | indent 4 }}
{{- end -}}
