image:
  repository: "ethereum/client-go"
  tag: "v1.8.23"
  pullPolicy: IfNotPresent

proxy:
  enabled: false
  rpcPort: 9545
  wsPort: 9546
  otpSecret: "<change-me>"
  image:
    pullPolicy: IfNotPresent
    repository: dysnix/protected-proxy
    tag: latest

rpcPort: 8545
wsPort: 8546
rpcApi: "net,eth,personal,web3"
rpcVhosts: "*"
wsApi: "net,eth,personal,web3"
wsOrigins: "*"
networkId: 1
testnet: false
rinkeby: false
syncMode: "fast"
customArgs: {}

service:
  type: ClusterIP
  annotations: {}
    # service.beta.kubernetes.io/aws-load-balancer-internal: ...

ingress:
  certmanagerClusterIssuer: letsencrypt-prod
  enabled: false
  rpc:
    proxyHosts:
    - rpc.example.com
    hosts:
    - secret-rpc.example.com
  ws:
    proxyHosts:
    - ws.example.com
    hosts:
    - secret-ws.example.com

persistence:
  enabled: true
  size: 250Gi
  # Use empty value for dynamic provisioning from snapshot
  storageClassName: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 1000m
  #   memory: 2000Mi
  # requests:
  #   cpu: 1000m
  #   memory: 2000Mi

hpa:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 300
