apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
{{ include "proxysql.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "proxysql.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "proxysql.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "proxysql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: ["proxysql", "-c", "/etc/proxysql/proxysql.cnf", "-f"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "proxysql.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: proxy
              containerPort: 6033
              protocol: TCP
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command: ["sh", "-c", "ss -n4 state listening | grep -wq '*:6033'"]
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data/proxysql
            - name: conf
              mountPath: /etc/proxysql
          {{- if .Values.ssl.fromSecret }}
            - name: ssl
              mountPath: /etc/proxysql/ssl
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: data
          emptyDir: {}
        - name: conf
          secret:
            secretName: {{ include "proxysql.fullname" . }}
            defaultMode: 0640
        {{- with .Values.ssl.fromSecret }}
        - name: ssl
          secret:
            secretName: {{ . }}
            defaultMode: 0640
        {{- end }}
