{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "proxysql.serviceAccountName" . }}
  labels:
{{ include "proxysql.labels" . | indent 4 }}
{{- end -}}
